name: CI
on: [workflow_dispatch, push]
jobs:
  tf-plan:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init + Plan
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform plan -input=false -no-color
