name: infra-apply
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  tf-apply:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud config set project "${{ secrets.PROJECT_ID }}"
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_wrapper: false }
      - name: Terraform Init
        working-directory: plm-infra/terraform
        run: terraform init -input=false
      - name: Terraform Apply
        working-directory: plm-infra/terraform
        env:
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_func_name: ec41-uploader
          TF_VAR_sa_email: cf-caller@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
        run: terraform apply -auto-approve -input=false
