name: IaC Apply
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'terraform/**' ]
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_DEPLOY_SA }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Terraform Init/Apply
        working-directory: terraform
        env:
          TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false
