name: tf state rm
on: workflow_dispatch
permissions:
  contents: read
  id-token: write

jobs:
  rm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Init
        run: terraform -chdir=terraform init -reconfigure -input=false -no-color
      - name: State rm
        run: |
          terraform -chdir=terraform state rm google_cloud_run_service_iam_member.run_invoker || true
          terraform -chdir=terraform state rm google_cloudfunctions2_function_iam_member.cf_invoker || true
