name: Terraform CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check -diff

      - name: Terraform init
        run: terraform -chdir=terraform init -reconfigure

      - name: Terraform validate
        run: terraform -chdir=terraform validate

      - name: Terraform plan
        run: terraform -chdir=terraform plan -lock=false -input=false -out=tfplan
