name: Terraform CI/CD
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: "true"
  GOOGLE_PROJECT: "leadgen-plm-prod-01"
  GOOGLE_REGION: "us-central1"

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/62450699138/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider2"
          service_account: "tf-plan-bot@leadgen-plm-prod-01.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - run: terraform -chdir=terraform fmt -check
      - run: terraform -chdir=terraform init -input=false
      - run: terraform -chdir=terraform validate
      - run: terraform -chdir=terraform plan -input=false -lock-timeout=5m -out=tfplan
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/62450699138/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider2"
          service_account: "tf-plan-bot@leadgen-plm-prod-01.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - run: terraform -chdir=terraform init -input=false
      - run: terraform -chdir=terraform apply -input=false -auto-approve
